### ISSUE TITLE
Kartenrotation soll zum Marker gespeichert werden

### ISSUE THREAD

**Issue by erictapen** [The-bastART/New-MRB-Mythology#1]
Wenn man dann auf den Marker drauf drückt, soll die Karte in die Orientierung rotieren, in der sie war als der Marker angelegt wurde.

**Comment by thatbastart** [comment]
hier ist wie gesagt (und gesehen) das problem, dass die popups bei einer rotierten karte an falschen positionen landen, d.h. damit das feature nützlich ist müsste wir herausfinden wieso bzw. wohin sich die popups jeweils verschieben und das css dynamisch anpassen

**Comment by erictapen** [comment]
Oha, mir war gar nicht klar, dass Upstream leaflet Rotation gar nicht unterstützt und dass wir dafür einen Fork benutzen: https://github.com/ronikar/Leaflet/tree/rotate-package

Ich fand leider nur wenig Dokumentation für `setBearing()`, deswegen ist mir das glaube ich zu mühselig, das zu implementieren. Hat denke ich schon einen Grund, warum upstream [das seit Jahren nicht integriert](https://github.com/Leaflet/Leaflet/issues/268), obwohl so viele Leute danach fragen. Mach das Ticket gerne wieder auf, falls du doch noch ne Möglichkeit siehst, Tilmann.

**Comment by thatbastart** [comment]
also das speichern ist ja eigtl easy; einfach die slider position in der submit auslesen und in nem popupopen event jeweils setzen
das eigtl problem ist wie gesagt die richtige positionierung des popups, die durch die rotation zerstört wird; ich öffne wieder, weil ich das schon cool fände, aber hat keinerlei priorität

**Comment by thatbastart** [comment]
hab jetzt mal in [1b48ed7](https://github.com/The-bastART/New-MRB-Mythology/commit/1b48ed77dadab8f5cef5675164deba5107817fae) die popup-rotation gefixt, allerdings etwas dirty: also hardcoded offsets für rotationen, die jetzt in 30° steps sind.
das einzige problem ist, dass nach rotation-slider verschieben und dann popup öffnen das pu noch falsch ist, aber nach dem ersten zoom läuft; absolut kA wieso. alles mögliche ausprobiert (reihenfolgen geändert etc.) kannst dich gerne mal dran versuchen und sonst die speicherung der rotation ggf auch implementieren

**Comment by thatbastart** [comment]
ok ich close jetzt doch wieder. die komplexität ist einfacher zu groß für so ein kleines (wenn auch cooles) feature. die popups werden sich bei rotation wieder schließen und die rotation wird wieder stufenlos
