### ISSUE TITLE
Typo-Vorschläge

### ISSUE THREAD

**Issue by thatbastart** [The-bastART/New-MRB-Mythology#10]
der titel ist aktuell Georgia und der rest undefiniert.

**Comment by Lariemouis** [comment]
ich überleg grad, vllt passt ja auch ne western schrift ganz gut? Such grad eine, die nicht so übertrieben nach Saloon schreit wie fast alle, aber vllt findet man ja eine, die auch bissi zum Mythology aspekt passt.

**Comment by thatbastart** [comment]
super idee!

**Comment by thatbastart** [comment]
![typo-variation](https://user-images.githubusercontent.com/13930660/103172276-abb1b380-4852-11eb-8e66-8890513d49d9.png)
habe mal Georgia & Helvetica zu GeoSlab & Titillium gemacht... ist dann auch eine Lizenzfrage mit denen, die wir ggf. haben wollen (GeoSlab hatte ich halt auf der Festplatte...; Titillium habe ich jetzt von Google Fonts eingebunden)

was meint ihr?

**Comment by erictapen** [comment]
![tmp nMmpyoROig](https://user-images.githubusercontent.com/11532355/103619864-c363f880-4f32-11eb-97c1-909cb762ac9d.png)
Bei mir im Firefox sieht der dünne Font oben links irgendwie arg zerbrechlich aus. Ich will nicht ausschließen, dass mein Fontrendering ein bisschen kaputt ist, aber könnten wir da vllt was fetteres/größeres nehmen? Ich hab da schon Schwierigkeiten, den I-Punkt von `Edit Mode` zu sehen.
