### ISSUE TITLE
Popup Text Edit

### ISSUE THREAD

**Issue by thatbastart** [The-bastART/New-MRB-Mythology#4]
nur text und kein html erlauben
links und einfaches formatieren wären trotzdem gut -> markdown integration machbar?

**Comment by thatbastart** [comment]
[https://github.com/Grafikart/JS-Markdown-Editor](https://github.com/Grafikart/JS-Markdown-Editor)
hat auch einen bild-uploader, den wir vllt nutzen können #3

**Comment by erictapen** [comment]
JS-Markdown-Editor scheint serverseitig PHP zu benutzen, damit kenne ich mich nicht aus. Würde das deswegen lieber nicht hosten.
