### ISSUE TITLE
StreetView

### ISSUE THREAD

**Issue by thatbastart** [The-bastART/New-MRB-Mythology#6]
Einbindung von StreetView -> split view; leaflet und StreetView Koordinaten laufen parallel (in StreetView der nächstmögliche punkt zur aktuellen leaflet position; evtl zu komplex!?)

**Comment by erictapen** [comment]
Also die [Streetview-API](https://developers.google.com/maps/documentation/streetview/overview) kostet wohl Geld. Beim bezahlen bin ich persönlich raus, hab keine Lust Geld an Google zu überweisen fürs Studium.

**Comment by thatbastart** [comment]
was zu befürchten war...
natürlich nicht.

**Comment by erictapen** [comment]
Dann close ich das erst mal?
