### ISSUE TITLE
Umgang mit neuen Markern / Leere Marker

### ISSUE THREAD

**Issue by thatbastart** [The-bastART/New-MRB-Mythology#7]
aktuell kann man im edit mode einfach marker hinzufügen ohne was einzutragen; dann werden beim nächsten anwählen natürlich noch die eingabefelder angezeigt
-> wenn felder im neuen marker nicht leer -> sperrung andere marker hinzuzufügen (und popup bleibt bis speichern oder verwerfen geöffnet!?); wenn felder im neuen marker leer -> self destruct

**Comment by thatbastart** [comment]
leere marker werden jetzt beim schließen entfernt;
wenn ein marker angefangen wurde wird gefragt ob die eingabe verworfen werden soll
wenn cancel und dann wieder schließen und diesmal verwerfen wird der marker aus irgendeinem grund nicht gelöscht; deswegen noch buggy; siehe [2c0e820](https://github.com/The-bastART/New-MRB-Mythology/commit/2c0e820ccc4c6bfb8947760eb120dd4b534a592a)

**Comment by erictapen** [comment]
Ist deployed.

**Comment by thatbastart** [comment]
das doppelt fragen kommt daher, dass remove nochmal close und damit confirm aufruft
